export const initialState = {
    query: "",
    data: [],
    searchDropDownValue: "Stories",
    byDropDownValue: "Popularity",
    forDropDownValue: "All Time",
    tagFilter: "(story,comment,poll)",
    sortFilter: "popularity",
    numericFilter: "created_at_i>1171843200",
    nbHits: "",
    processingTimeMS: "",
    page: 0,
    nbPages: 0,
    active: 0,
};